export const guitars = [
    {
        name: "2019 MARTIN D-41 - NATURAL",
        short: "martin-d-41",
        img: `${process.env.PUBLIC_URL + '/guitars/martin-d41.jpeg'}`,
        moreImg: [`${process.env.PUBLIC_URL + '/guitars/martin-d41.jpeg'}`, `${process.env.PUBLIC_URL + '/guitars/martin-d41.jpeg'}`, `${process.env.PUBLIC_URL + '/guitars/martin-d41.jpeg'}`, `${process.env.PUBLIC_URL + '/guitars/martin-d41.jpeg'}`],
        price: 12000,
        descr: [`2019 Martin D-41 - Natural/aging toner finish with the original hard-case. This guitar is in near mint condition and perfect working order. There are no obvious signs of play-wear apart from some extremely faint scuffs on the back and sides of the body and some some on the pickguard. They are so faint and small you have to hold the guitar up to the light and look very closely. There are no cracks, repairs, or issues. The neck is straight with no issues and the truss rod works as it should. The original frets have no wear at all.`, `It's been fully checked over in our workshop and set up with a fresh set of strings and a great action. Nut width:45 mm. Depth at 1st fret 21 mm. Weight: 4 lbs 10.5 oz. Serial:2330455. 3-month warranty included. `, `Inlaid in stunning abalone pearl and appointed with gold tuners, it's more than a Dreadnought: it's an heirloom. Premium East Indian rosewood and Sitka spruce combined with hand-carved scalloped bracing to produce rich, powerful, complex tone. The mahogany neck features Martin's 'Modified Low Oval' carve which feels to me like a very soft V. This makes for an exceptionally comfortable playing experience. The back of the headstock features a carved diamond volute adding strength to the scarf joint.`],
        condition: "Near mint",
        case: "OHSC",
        weight: 2.2,
        serial: 2330455,
        type: "acoustic",
        isActive: true,
        sold: false,
    },
    {
        name: "2021 GIBSON J-185 ORIGINAL - VINTAGE SUNBURST",
        short: "gibson-j-185",
        img: `${process.env.PUBLIC_URL + '/guitars/gibson-vintage.jpeg'}`,
        moreImg: [`${process.env.PUBLIC_URL + '/guitars/gibson-vintage.jpeg'}`, `${process.env.PUBLIC_URL + '/guitars/gibson-vintage.jpeg'}`, `${process.env.PUBLIC_URL + '/guitars/gibson-vintage.jpeg'}`, `${process.env.PUBLIC_URL + '/guitars/gibson-vintage.jpeg'}`],
        price: 15000,
        descr: [`2021 Gibson J-185 Original - Vintage Sunburst in mint/unplayed condition - you will be the first owner to play this acoustic! The J-185 is believed by many to be one of Gibson's best acoustic instruments, yet it seems to be fairly obscure, much to the delight of devoted Gibson lovers. Originally released in the early 1950s and designed to be slightly smaller than its larger companion, the SJ-200, the J-185 still offers superior performance and tone. The J-185 Original maintains unsurpassed balance of lows, mids, and highs, with equal response to every note on the fretboard. Acclaimed by many as the perfect body size and shape for any player. `, `Sitka spruce top with flamed maple back and sides. Traditional hand scalloped x-bracing. Multy-ply binding to the top and back. Nitrocellulose finish. `, ` Slim taper mahogany neck with a 20 fret rosewood fingerboard and a 12" radius and a bone nut. Gotoh Keystone tuners, bone saddle, tusk pins. LR Baggs VTC under saddle pickup with the volume and tone controls in the soundhole.`],
        condition: "-",
        case: "-",
        weight: "-",
        serial: "-",
        type: "acoustic",
        isActive: true,
        sold: false,
    },
    {
        name: "1966 FENDER JAGUAR, SUNBURST",
        short: "fender-jaguar",
        img: `${process.env.PUBLIC_URL + '/guitars/fender-jaguar.jpeg'}`,
        moreImg: [`${process.env.PUBLIC_URL + '/guitars/fender-jaguar.jpeg'}`, `${process.env.PUBLIC_URL + '/guitars/fender-jaguar.jpeg'}`, `${process.env.PUBLIC_URL + '/guitars/fender-jaguar.jpeg'}`, `${process.env.PUBLIC_URL + '/guitars/fender-jaguar.jpeg'}`],
        price: 22000,
        descr: [`1966 Fender Jaguar with a Sunburst finish in excellent condition. It has a tortoise pickguard and a rosewood fingerboard with a bound neck. All original including the case, the only thing missing is the bridge cover. 3-month warranty included.`, `The only wear of any significance is to be found around the edges where there are numerous small scuffs and dings particularly along the bottom edge of the body. The frets have been dressed in our workshop and have plenty of life left in them. The truss rod is fully functional with no issues. The back of the neck is clean overall with only minor play wear. `, `This guitar has been set up in our workshop with a fresh set of D'Addario 10 gauge strings and a low action. The neck is stamped FEB 66 B. Serial 158754. The volume pot dates to the 12th week of 66. The tone pot dates to the 45th week of 65. Original gray/green bobbin pickups. Weight 8 lbs 10 oz. Nut width: 42 mm. Depth at 1st fret: 21.5 mm. Depth at 12th fret: 23.5 mm.`, `The Jaguar was launched in 1962 as another top-of-the-line guitar in the same vein as the Jazzmaster. Both guitars shared the modern offset body shape and distinct floating tremolo system. The Jaguar differed in its use of a shorter 24-inch scale length and stronger single-coil pickups, which were encased in notched covers to shield the electronics from external radio noise (a typical annoyance with the Jazzmasters soapbars). Both guitars integrated a unique dual rhythm-lead circuit design, yet on the Jaguar the lead circuit includes three switches: on-off for the front pickup, on-off for the back pickup, and a bass-cut switch that adds an extra capacitor to the signal.`],
        condition: "Excellent",
        case: "OHSC",
        weight: 4.1,
        serial: 158754,
        type: "solid",
        isActive: true,
        sold: false,
    },
    {
        name: "1971 GIBSON ES-335 TDC, CHERRY",
        short: "gibson-es-335",
        img: `${process.env.PUBLIC_URL + '/guitars/gibson-cherry.jpeg'}`,
        moreImg: [`${process.env.PUBLIC_URL + '/guitars/gibson-cherry.jpeg'}`, `${process.env.PUBLIC_URL + '/guitars/gibson-cherry.jpeg'}`, `${process.env.PUBLIC_URL + '/guitars/gibson-cherry.jpeg'}`],
        price: 23000,
        descr: [`1971 Gibson ES-335 TDC, Cherry finish in excellent condition. All original including the case. It has a great sounding pair of "Patent Number" humbucking pickups, a trapeze tailpiece with ABR-1 bridge, great playing, mahogany neck, and "double-ring" Kluson tuners. The visible pot date is 137 710x ( the x being covered in solder).`, `This guitar has been fully checked over & set up in our workshop and is an all-round excellent sounding and playing guitar. Set up with a low action allowing for very smooth movement around the fretboard. It has a big rich tone both plugged in and acoustically. Nut width: 40 mm. Depth at 1st fret: 19.6 mm.  Depth at 12th fret: 24.2 mm. Serial:637456. Weight: 7lbs 9.5oz.`, `The finish on the front and back is mostly free of wear with only has a few small scuffs. The frets are in great shape with plenty of life left in them and all hardware & electronics are in excellent working order. The back of the neck and headstock are clean overall with just a few very small marks in the finish and some small dings along the top edge of the headstock. There are no breaks or repairs. Everything remains structurally sound. There is an imprint of a washer around each tuning post suggesting other tuners were previously fitted, however the bushings fit nice and snug so theres no issues with them moving about. There are no extra holes in the back of the headstock. /n The ES335 is Semi-Hollow it has a Maple front back & sides, double cutaway arched Maple top with f-holes, layered Black pickguard, Trapeze tailpiece, Rosewood fretboard with block inlays, 2 covered pickups; 2 volume, 2 tone controls with 3 position switch. Black headstock faceplate with pearl crown logo & 3 per side tuners.`],
        condition: "Excellent",
        case: "OHSC",
        weight: 3.7,
        serial: 637456,
        type: "hollow",
        isActive: true,
        sold: false,
    },
    {
        name: "1971 GIBSON ES-335 TDC, CHERRY",
        short: "gibson-es-335-2",
        img: `${process.env.PUBLIC_URL + '/guitars/gibson-cherry.jpeg'}`,
        moreImg: [`${process.env.PUBLIC_URL + '/guitars/gibson-cherry.jpeg'}`, `${process.env.PUBLIC_URL + '/guitars/gibson-cherry.jpeg'}`, `${process.env.PUBLIC_URL + '/guitars/gibson-cherry.jpeg'}`, `${process.env.PUBLIC_URL + '/guitars/gibson-cherry.jpeg'}`, `${process.env.PUBLIC_URL + '/guitars/gibson-cherry.jpeg'}`],
        price: 23000,
        descr: [`1971 Gibson ES-335 TDC, Cherry finish in excellent condition. All original including the case. It has a great sounding pair of "Patent Number" humbucking pickups, a trapeze tailpiece with ABR-1 bridge, great playing, mahogany neck, and "double-ring" Kluson tuners. The visible pot date is 137 710x ( the x being covered in solder).`, `This guitar has been fully checked over & set up in our workshop and is an all-round excellent sounding and playing guitar. Set up with a low action allowing for very smooth movement around the fretboard. It has a big rich tone both plugged in and acoustically. Nut width: 40 mm. Depth at 1st fret: 19.6 mm.  Depth at 12th fret: 24.2 mm. Serial:637456. Weight: 7lbs 9.5oz.`, `The finish on the front and back is mostly free of wear with only has a few small scuffs. The frets are in great shape with plenty of life left in them and all hardware & electronics are in excellent working order. The back of the neck and headstock are clean overall with just a few very small marks in the finish and some small dings along the top edge of the headstock. There are no breaks or repairs. Everything remains structurally sound. There is an imprint of a washer around each tuning post suggesting other tuners were previously fitted, however the bushings fit nice and snug so theres no issues with them moving about. There are no extra holes in the back of the headstock. /n The ES335 is Semi-Hollow it has a Maple front back & sides, double cutaway arched Maple top with f-holes, layered Black pickguard, Trapeze tailpiece, Rosewood fretboard with block inlays, 2 covered pickups; 2 volume, 2 tone controls with 3 position switch. Black headstock faceplate with pearl crown logo & 3 per side tuners.`],
        condition: "Excellent",
        case: "OHSC",
        weight: 3.7,
        serial: 637456,
        type: "hollow",
        isActive: true,
        sold: false,
    }
]
